const SINGER_LIST_REQUEST = "SINGER_LIST_REQUEST";
const SINGER_LIST_FAILURE = "SINGER_LIST_FAILURE";
const SINGER_SET_CURRENT_SHORTCUR = "SINGER_SET_CURRENT_SHORTCUR";

export {
  SINGER_LIST_REQUEST,
  SINGER_LIST_FAILURE,
  SINGER_SET_CURRENT_SHORTCUR
};
