export const SET_PLAY_LIST = "SET_PLAY_LIST";
export const SET_FULL_SCREEN = "SET_FULL_SCREEN";
export const SET_PLAYING_STATE = "SET_PLAYING_STATE";
export const SET_CURRENT_SONG_ID = "SET_CURRENT_SONG_ID";
